import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="p-5 sm:p-8 md:p-12 lg:p-16 xl:p-20 overflow-x-hidden">{children}</body>
      
    </html>
  );
}


